#########

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMyNDA1ODN9.7xhpR6T-zkUdV9Pqzbr4mnM-CtpZC-3a9HnhdhHhd-Q

#########



### ACTORS show
GET http://localhost:3000/actors/1.json
Authorization: Bearer {{jwt}}

### ACTORS index

GET http://localhost:3000/actors.json
Authorization: Bearer {{jwt}}

### ACTORS create

POST http://localhost:3000/actors.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "",
  "last_name": "",
  "known_for": "",
  "gender": "",
  "age": 1,
  "movie_id": 1 
}

### ACTORS update

PATCH http://localhost:3000/actors/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    
}

### ACTORS delete

DELETE http://localhost:3000/actors/3
Authorization: Bearer {{jwt}}

### MOVIES index

GET http://localhost:3000/movies
Authorization: Bearer {{jwt}}

### MOVIES show

GET http://localhost:3000/movies/1
Authorization: Bearer {{jwt}}

### MOVIES create

POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "title": "Pirates of the Caribbean",
    "year": 2003,
    "plot": "Capt. Jack Sparrow arrives at Port Royal in the Caribbean without a ship or crew. His timing is inopportune, however, because later that evening the town is besieged by a pirate ship. The pirates kidnap the governor's daughter, Elizabeth, who's in possession of a valuable coin that is linked to a curse that has transformed the pirates into the undead. A gallant blacksmith in love with Elizabeth allies with Sparrow in pursuit of the pirates."
}

### MOVIES update

PATCH http://localhost:3000/movies/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "year": 2017
}

### MOVIES destroy

DELETE http://localhost:3000/movies/4
Authorization: Bearer {{jwt}}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name1",
  "email": "test1@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}